name: Publish beta version

on:
  workflow_dispatch:

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build

      - name: Set NPM Token
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Set current commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get current released version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Publish
        run: npm run pub:beta
        env:
          BETA_VERSION: ${{ steps.package-version.outputs.current-version}}-beta.${{ steps.vars.outputs.sha_short }}
